Controllers/VersionController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using WebApiAssignment1.BusinessLayer;
using WebApiAssignment1.Models.EntityLayer;

namespace WebApiAssignment1.Controllers
{
    public class VersionController : Controller
    {
        public async Task<ActionResult> Index()
        {
            Customer customer = new Customer();
            IEnumerable<Customer> cust = null;
            HttpClient client = new HttpClient();

            client.BaseAddress = new Uri("http://localhost:61680");
            try
            {
                var consumeData = await client.GetAsync("Api/Version1Api");
                if (consumeData.IsSuccessStatusCode)
                {
                    var results = await consumeData.Content.ReadAsAsync<IList<Customer>>();
                    cust = results;
                }
                else
                {
                    cust = Enumerable.Empty<Customer>();
                    ModelState.AddModelError(string.Empty, "Server error. Please contact administrator.");
                }
            }
            catch (Exception)
            {
                cust = Enumerable.Empty<Customer>();
                ModelState.AddModelError(string.Empty, "Error connecting to the server.");
            }


            ViewBag.res = TempData["Message"];
            return View(cust);
        }

        public ActionResult InsertCust()
        {
            return View();
        }

        [HttpPost]

        public async Task<ActionResult> InsertCust(Customer customer)
        {
            if (!ModelState.IsValid)
            {
                return View(customer);
            }

            HttpClient client = new HttpClient();

            client.BaseAddress = new Uri("http://localhost:61680");


            var content = new StringContent(JsonConvert.SerializeObject(customer), Encoding.UTF8, "application/json");

            HttpResponseMessage consumeData = await client.PostAsync("Api/Version1Api", content);

            if (consumeData.IsSuccessStatusCode)
            {
                string Message = await consumeData.Content.ReadAsStringAsync();
                TempData["Message"] = Message;
                return RedirectToAction("Index");
            }
            else
            {

                ModelState.AddModelError(string.Empty, "Server error. Please contact the administrator.");
                return RedirectToAction("Index");
            }

        }

        public ActionResult UpdateCust(int id)
        {
            CustomerService customerService = new CustomerService();

            Customer cust = customerService.GetCustomerByID(id);

            TempData["ID"] = id;
            return View(cust);
        }

        [HttpPost]

        public async Task<ActionResult> UpdateCust(Customer customer)
        {
            customer.Id = Convert.ToInt32(TempData["ID"]);
            HttpClient httpClient = new HttpClient();
            httpClient.BaseAddress = new Uri("http://localhost:61680");

            var content = new StringContent(JsonConvert.SerializeObject(customer), Encoding.UTF8, "application/json");

            HttpResponseMessage consumeData = await httpClient.PutAsync("Api/Version1Api", content);

            if (consumeData.IsSuccessStatusCode)
            {
                string Message = await consumeData.Content.ReadAsStringAsync();
                TempData["Message"] = Message;
                return RedirectToAction("Index");
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Server error. Please contact the administrator.");
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public async Task<ActionResult> DeleteCust(int id)
        {
            HttpClient httpClient = new HttpClient();
            httpClient.BaseAddress = new Uri("http://localhost:61680/");
            HttpResponseMessage consumeData = await httpClient.DeleteAsync($"Api/Version2Api/{id}");

            if (consumeData.IsSuccessStatusCode)
            {
                string Message = await consumeData.Content.ReadAsStringAsync();
                TempData["Message"] = Message;
                return RedirectToAction("Index");
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Server error. Please contact the administrator.");
                return RedirectToAction("Index");
            }
        }
    }
}

Views/Version/Index.cshtml
@model IEnumerable<WebApiAssignment1.Models.EntityLayer.Customer>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "InsertCust","Version")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Gender)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Phone)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.UserName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Gender)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Address)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Phone)
        </td>
        <td>
            @Html.ActionLink("UPDATE", "UpdateCust","Version", new { id = item.Id }, new { @class = "btn btn-warning" })
            @using (Html.BeginForm("DeleteCust", "Version", new { id = item.Id }, FormMethod.Post, new { @class = "d-inline", id = "deleteForm" + item.Id }))
            {
                <button type="submit" class="btn btn-danger">DELETE</button>
            }
        </td>
    </tr>
}

</table>

Views/Version/InsertCust.cshtml
@model WebApiAssignment1.Models.EntityLayer.Customer

@{
    ViewBag.Title = "InsertCust";
}

<h2>InsertCust</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Customer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Gender, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Version/UpdateCust.cshtml
@model WebApiAssignment1.Models.EntityLayer.Customer

@{
    ViewBag.Title = "UpdateCust";
}

<h2>UpdateCust</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Customer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Gender, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}